// Generated by https://quicktype.io

export interface QuizQuestionsResponse {
  response_code: number;
  results: QuizQuestionsResult[];
}

export interface QuizQuestionsResult {
  category: Category;
  type: Type;
  difficulty: Difficulty;
  question: string;
  correct_answer: string;
  incorrect_answers: string[];
}

export enum Category {
  Animals = "Animals",
}

export enum Difficulty {
  Easy = "easy",
  Hard = "hard",
  Medium = "medium",
}

export enum Type {
  Multiple = "multiple",
}
